### ISSUE TITLE
Installing Pyramid using Julia 1.6.1

### ISSUE THREAD

**Issue by peaceben** [ian-small/pyrimid#1]
Hi,

I'm not very familiar with Julia. I've installed Julia and all required packages, but failed at installing/cloning the pyramid git repository itself.

_Pkg.add(url="https://github.com/ian-small/pyrimid.git")_

Did not work for me and gives:

_ERROR: could not find project file in package at `https://github.com/ian-small/pyrimid.git` maybe `subdir` needs to be specified_

A quick google led me to think it might be a due to switch between Julia versions to using Project.toml files. Could you help me out here? 

Best regards,
Ben

**Comment by ian-small** [comment]
Hi Ben,

I’m certainly a neophyte at Julia, just experimenting…
Pyrimid isn’t set up as a Package (but I should probably do that!) which is why what you tried didn’t work.
You can just download the source code directly or via git clone and it should work

julia pyrimid/src/pyrimid.jl  [--mapQ MAPQ] [--baseQ BASEQ] [-w CONTEXTWINDOW] [--single-end] [--paired-end] [-f] [-u] [-o OUTFILE] reference bam

Out of interest, what are you intending to do with it?

Cheers
Ian


From: peaceben ***@***.***>
Date: Wednesday, 30 June 2021 at 8:17 pm
To: ian-small/pyrimid ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ian-small/pyrimid] Installing Pyramid using Julia 1.6.1 (#1)

Hi,

I'm not very familiar with Julia. I've installed Julia and all required packages, but failed at installing/cloning the pyramid git repository itself.

Pkg.add(url="https://github.com/ian-small/pyrimid.git<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fian-small%2Fpyrimid.git&data=04%7C01%7Cian.small%40uwa.edu.au%7Cddea57790aa64ecf173408d93bc106ac%7C05894af0cb2846d8871674cdb46e2226%7C1%7C0%7C637606522493319411%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=p3QgRIz2hqCJUu0WFQUNV27yMv%2F36HTCBJ2yN%2BG0EDw%3D&reserved=0>")

Did not work for me and gives:

ERROR: could not find project file in package at https://github.com/ian-small/pyrimid.git maybe subdir needs to be specified

A quick google led me to think it might be a due to switch between Julia versions to using Project.toml files. Could you help me out here?

Best regards,
Ben

**Comment by peaceben** [comment]
Hi Ian,

classic case of: When you hear hooves, think horse, not zebra. Thanks!

I'm currently trying out different computational approaches for (plant-related) RNA-editing analysis. We want to enable more people in our group (Schmitz-Linneweber lab) to perform thier own basic RNA-seq analysis and I'm currently in the process of assembleing a tool box for this.

Best,
Ben
